<?php

/**
 * @file
 * Contains drupal_api_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_api_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupal_api_block module.
    case 'help.page.drupal_api_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Description') . '</p>';
      return $output;

    default:
  }
}
